//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaContactos_DAM
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Lista_Contactos
    {
        public string DNI { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string email { get; set; }
        public string Telefono { get; set; }
        public Nullable<System.DateTime> Fecha_Alta { get; set; }
        public Nullable<double> Sueldo { get; set; }
        public Nullable<System.DateTime> Fecha_Baja { get; set; }
    }
}
